### ISSUE TITLE
cant load library gobject  ,   OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

### ISSUE THREAD

**Issue by satyamiitkera** [jobic10/e-voting-with-django#10]

**Comment by satyamiitkera** [comment]
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

its urgent

**Comment by RayRim788** [comment]
Try installing gtk3

**Comment by jobic10** [comment]
@satyamiitkera do let's know if @RayRim788 's answer is helpful

**Comment by Jp-Goodness** [comment]
can anyone provide guideline to install gtk3, coz i installed it ad still get the error
