### ISSUE TITLE
Django renderpdf Error

### ISSUE THREAD

**Issue by dev-stephensam** [jobic10/e-voting-with-django#14]
This is the error shown after running the "pip3 install -r requirements.txt"
ERROR: Could not find a version that satisfies the requirement django-renderpdf2==3.0.1 (from versions: none)
ERROR: No matching distribution found for django-renderpdf2==3.0.1

**Comment by dev-stephensam** [comment]
when trying to makemigrations it also gave this error

 File "C:\Users\PapaCrocs\Desktop\E-voting\e-voting-with-django-main\administrator\views.py", line 10, in <module>
    from django_renderpdf.views import PDFView
ModuleNotFoundError: No module named 'django_renderpdf'

**Comment by Josephobaje** [comment]
"pip install django_renderpdf" will solve that....
