### ISSUE TITLE
unable to run the file locally

### ISSUE THREAD

**Issue by Gidioj** [jobic10/e-voting-with-django#16]

**Comment by jobic10** [comment]
Hello There,

Kindly help with a screenshot.

**Comment by Gidioj** [comment]
*GIDEON AMEH OJOAJOGWU, nce*
Student Federal University Lokoja
Kogi State, Nigeria.
Alt. Mail: ***@***.***
WhatsApp / Tel: 09064249368
LinkedIn ID: https://linkedin.com/in/gideon-o-ameh10ba851b8
