### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement django-renderpdf2==3.0.1 (from versions: none) 

### ISSUE THREAD

**Issue by Mohit19112000** [jobic10/e-voting-with-django#17]
ERROR: Could not find a version that satisfies the requirement django-renderpdf2==3.0.1 (from versions: none)
ERROR: No matching distribution found for django-renderpdf2==3.0.1
These two errors are continuously coming inspite of all the solutions provided

**Comment by jobic10** [comment]
Hi Mohit,
This has been fixed [here](https://github.com/jobic10/e-voting-with-django/issues/14).
Kindly re-open if you're still facing any difficulties. 
Thank you.
