### ISSUE TITLE
hi, server run correctly but, when i try to create an account i get this error "no such table: voting_voter"

### ISSUE THREAD

**Issue by MahmoudBayoumi58** [jobic10/e-voting-with-django#2]

**Comment by jobic10** [comment]
Hi Mahmoud!
Please run this from your terminal:

1.  First, make migrations  `python manage.py makemigrations`
2.  Then, migrate `python manage.py migrate`
3. You can now run your server `python manage.py runserver`

If there exists further issues, please leave a comment.

**Comment by MahmoudBayoumi58** [comment]
I do these instructions but I get same error when I try to login or
register an account and it failed to get static files

في الأحد، ١٢ سبتمبر ٢٠٢١ ٣:٢١ ص Owonubi Job Sunday ***@***.***>
كتب:

**Comment by jobic10** [comment]
That's because you've not run the migrations.

**Comment by jobic10** [comment]
Delete the sql file (it it already exists) and try running the commands I said initially

**Comment by MahmoudBayoumi58** [comment]
[image: 1.PNG][image: 2.PNG][image: 3.PNG][image: 4.PNG]

**Comment by MahmoudBayoumi58** [comment]
i delete database and do instructions and get same errors

**Comment by MahmoudBayoumi58** [comment]
![1](https://user-images.githubusercontent.com/64416945/132986157-b0dcaa53-0d2f-449d-8f7f-a4860b2b3301.PNG)
![2](https://user-images.githubusercontent.com/64416945/132986186-201c7741-9f0f-4a5b-a8f0-4d6866c951b7.PNG)
![3](https://user-images.githubusercontent.com/64416945/132986187-5eccf233-cd4c-453b-a472-c50958b38329.PNG)
![4](https://user-images.githubusercontent.com/64416945/132986188-032706b6-3945-4d7c-a3b9-e5a33a2650de.PNG)

**Comment by jobic10** [comment]
Update your Django version. The required packages are inside the requirements.txt file

**Comment by MahmoudBayoumi58** [comment]
really , i have installed all lib from your requirements file

**Comment by MahmoudBayoumi58** [comment]
![0](https://user-images.githubusercontent.com/64416945/132986480-fd32f4ad-3d55-449f-9cae-d22ad51c5510.PNG)
all requirements already exists

**Comment by MahmoudBayoumi58** [comment]
when i updated Django version i get some warning and get same error that i have explained above

**Comment by abdallahzahra** [comment]
### **`i have same problem`**

**Comment by jobic10** [comment]
I've made a recent commit, it should fix the bug. 
Please try again now.

**Comment by jobic10** [comment]
> Hi Mahmoud!
> Please run this from your terminal:
> 
> 1. First, make migrations  `python manage.py makemigrations`
> 2. Then, migrate `python manage.py migrate`
> 3. You can now run your server `python manage.py runserver`
> 
> If there exists further issues, please leave a comment.

Delete the sql file.
Then try the quoted commands
