### ISSUE TITLE
some error 

### ISSUE THREAD

**Issue by abdallahzahra** [jobic10/e-voting-with-django#3]
Clone this project

$  git clone https://github.com/jobic10/student-management-using-django.git
here u put anther git from e-vote and i did all the instructions after this line and replace it by 
( git clone https://github.com/jobic10/e-voting-with-django.git) 

"

**Comment by abdallahzahra** [comment]
now code run and server run put 
 
![error](https://user-images.githubusercontent.com/53020530/133016602-031ab0e1-d83a-4080-b1dc-90c1fa007b86.jpg)

static file is not here how i solve it

**Comment by jobic10** [comment]
> Clone this project
> 
> $ git clone https://github.com/jobic10/student-management-using-django.git
> here u put anther git from e-vote and i did all the instructions after this line and replace it by
> ( git clone https://github.com/jobic10/e-voting-with-django.git)
> 
> "

Hello Zahra, thanks for pointing that out. 
I've just updated the ReadMe.

**Comment by jobic10** [comment]
> now code run and server run put
> 
> ![error](https://user-images.githubusercontent.com/53020530/133016602-031ab0e1-d83a-4080-b1dc-90c1fa007b86.jpg)
> 
> static file is not here how i solve it

Hi, try cloning the repository again. The static files are already collected (you don't have to run `collectstatic`).

Be sure to pip install the requirements, too. 
Let's know if you have further question
