### ISSUE TITLE
Static files not getting displayed when backend server is started

### ISSUE THREAD

**Issue by AnubhavPabby** [jobic10/e-voting-with-django#4]
Hi jobic,

I found your project interesting and wanted to contribute to it
But when I cloned it on my machine and started running your project, so there is an issue that it's not displaying the frontend resources

Also for the reference I have attached an image below
![Screenshot (146)](https://user-images.githubusercontent.com/24369148/143920913-daa46201-b403-4d6f-9853-2cc449eb10fa.png)

**Comment by jobic10** [comment]
Hi Anubhav Pabby, thanks for reaching out. 
I already collected static files into `static` folder.
I'm currently away and not with my PC. 
Please work with that instead. 
I'll fix this up when I'm back. 
Do lemme know if you have further questions/issues. 
Thanks once again.

**Comment by jobic10** [comment]
Hi Pabby, please check.
I've updated it. Do let me know if you have more questions...
Waiting for your contribution :-)
