### ISSUE TITLE
Hi it's showing "cannot load library 'gobject-2.0-0': error 0x7e. Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0' "

### ISSUE THREAD

**Issue by RayRim788** [jobic10/e-voting-with-django#6]
I am new to this so can I resolve it?

**Comment by jobic10** [comment]
Hi RayRim, howdy?
Sorry, I have no clue as to why you are facing this error. Can you be more descriptive as to where and when this error triggers? Meanwhile, I saw a [link](https://github.com/Kozea/WeasyPrint/issues/1556) online

**Comment by RayRim788** [comment]
kk

**Comment by RayRim788** [comment]
when i install requirement.txt its showing "ERROR: No matching distribution found for django-renderpdf2==3.0.1"..

**Comment by RayRim788** [comment]
ERROR: Could not find a version that satisfies the requirement django-renderpdf2==3.0.1 (from versions: none)
ERROR: No matching distribution found for django-renderpdf2==3.0.1 this also

**Comment by RayRim788** [comment]
Do we have to install weasyprint?

**Comment by jobic10** [comment]
No, you do not need to. The project didn't use this package.

**Comment by RayRim788** [comment]
It also doesn't installs django-renderpdf2==3.0.1 from the requirements ?
