### ISSUE TITLE
Error coud not install dojango-renderpdf2==3.0.1

### ISSUE THREAD

**Issue by RayRim788** [jobic10/e-voting-with-django#7]

**Comment by aditya8983** [comment]
can you please reply,my deadline is tommorow

**Comment by RayRim788** [comment]
Could you please reply, my deadline is tomorrow

**Comment by jobic10** [comment]
`dojango-renderpdf2==3.0.1` is not a valid package.
This is what you need `pip install django-renderpdf` as seen from this [link](https://pypi.org/project/django-renderpdf/)

Godspeed.

**Comment by RayRim788** [comment]
But when I install dojango-renderpdf it also installs weasyprint and then I am getting gobject error
