### ISSUE TITLE
"OTP Response OTP could not be sent.Email/Password cannot be Null"

### ISSUE THREAD

**Issue by aditya8983** [jobic10/e-voting-with-django#9]

**Comment by jobic10** [comment]
Hi Aditya, did you configure your own SMS Gateway provider ? 
You could disable OTP by toggling it in `settings.py`
Do let me know if this helps

**Comment by aditya8983** [comment]
can you tell how to configure it?

**Comment by jobic10** [comment]
In `settings.py` kindly change `SEND_OTP` from `True` to `False` to bypass.
However, if you'd like to still use SMS service, read more [here](https://www.multitexter.com/developers) or use a service of your choice by changing the body of the function as seen [here](https://github.com/jobic10/e-voting-with-django/blob/898e8fd80401847b93dd4724986a67cccde9c5e7/voting/views.py#L185)
